services:

  # lama-rv:
  #   build: .
  #   entrypoint: ["/bin/sh"]
  #   stdin_open: true
  #   tty: true

  lama-rv-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lama-rv-test      
    volumes:
      - ./:/workspace
    working_dir: /workspace
    platform: linux/amd64
    environment:
      LAMA_RV_BACKEND: /workspace/comp/src/lama_rv.cpp
    entrypoint: ["/bin/bash"]
    stdin_open: true
    tty: true
  
  # lama-rv-benchmark:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: lama-rv-benchmark  
  #   volumes:
  #     - ./:/workspace
  #   working_dir: /workspace
  #   environment:
  #     LAMA_RV_BACKEND: /workspace/comp/src/lama_rv.cpp
  #   command: ["make", "-C", "performance", "check"]